### ISSUE TITLE
autocomplete target_{INCLUDE_DIRS, DEFINITIONS, SOURCE_DIR, LIBRARIES} etc

### ISSUE THREAD

**Issue by GopherJ** [vhdirk/vim-cmake#32]
Hi, is it possible to support target suffix autocompletion?

Like:

- LIBRARIES
- INCLUDE_DIRS
- DEFINITIONS
- SOURCE_DIR

etc

the keyword for triggering this will be `_`, and before `_` it must be a target

**Comment by Drvanon** [comment]
A useful command to get a list of all possible cmake targets is: `cmake --build . --target help`

**Comment by Drvanon** [comment]
Probably the code should look something like
```vim
com -complete=custom,ListTargets -nargs=1 make :make <args>
function! ListTargets(A, L, C)
    return split(system("cmake --build ". b:build_dir . " --target help"), '\n')
endfunction

```

**Comment by Drvanon** [comment]
You can add this to your .vimrc and it will add the feature for you. Note that you will have to work with :Make instead of :make.
