### ISSUE TITLE
Feature request: Allow scroll while building

### ISSUE THREAD

**Issue by bharatvaj** [vhdirk/vim-cmake#35]
It seems like the scroll won't work when the cmake window is building something. It would be awesome if that's possible!

**Comment by lrittel** [comment]
Btw: `:CMake` supports this by using asyncrun.vm and for `:make` it's not an vim-cmake-issue but a vim one. There exist multiple other plugins to implement this functionality, though. Just look for „async `:make`“.

**Comment by bharatvaj** [comment]
Cool! Thanks for the tip. I'll close this issue.
